<!-- MDTOC maxdepth:6 firsth1:1 numbering:0 flatten:0 bullets:1 updateOnSave:1 -->

- [常用内置函数](#常用内置函数)   
   - [func make(t Type, size ...IntegerType) Type](#func-maket-type-size-integertype-type)   
   - [func new(Type) *Type](#func-newtype-type)   
   - [func close(c chan<- Type)](#func-closec-chan-type)   
   - [func print(args ...Type)](#func-printargs-type)   
   - [func println(args ...Type)](#func-printlnargs-type)   
   - [func len(v Type) int](#func-lenv-type-int)   
   - [func delete(m map[Type]Type1, key Type)](#func-deletem-maptypetype1-key-type)   
   - [func copy(dst, src []Type) int](#func-copydst-src-type-int)   
   - [func append(slice []Type, elems ...Type) []Type](#func-appendslice-type-elems-type-type)   
   - [func cap(v Type) int](#func-capv-type-int)   
   - [func panic(v interface{})](#func-panicv-interface)   
   - [func recover() interface{}](#func-recover-interface)   

<!-- /MDTOC -->
# 常用内置函数

## func make(t Type, size ...IntegerType) Type

## func new(Type) *Type

## func close(c chan<- Type)

## func print(args ...Type)

## func println(args ...Type)

## func len(v Type) int

```
// The len built-in function returns the length of v, according to its type:
//	Array: the number of elements in v.
//	Pointer to array: the number of elements in *v (even if v is nil).
//	Slice, or map: the number of elements in v; if v is nil, len(v) is zero.
//	String: the number of bytes in v.
//	Channel: the number of elements queued (unread) in the channel buffer;
//	if v is nil, len(v) is zero.
func len(v Type) int
```






## func delete(m map[Type]Type1, key Type)

* delete函数用于删除map中对应key的键值对，如果map中不存在该key，则什么也不做
* 一般用来删除map键值对，根据参数列表，显而易见。
* 没有返回值
* 提供不存在的键不影响，只能通过键来删除
* 不能删除类型不匹配的键

```
	m1 := make(map[int]string)
	m1[1] = "1"
	m1[2] = "2"
	m1[3] = "3"
	fmt.Printf("%v", m1) // map[1:1 2:2 3:3]
	delete(m1,1)
	delete(m1,9)
	fmt.Printf("%v", m1) // map[2:2 3:3]
	delete(m1,"123")
	fmt.Printf("%v", m1) // cannot use "123" (type string) as type int in delete
```




## func copy(dst, src []Type) int

## func append(slice []Type, elems ...Type) []Type

* elems若为切片需要解包...

```
var a []int
a = append(a, 1) // 追加1个元素
a = append(a, 1, 2, 3) // 追加多个元素, 手写解包方式
a = append(a, []int{1,2,3}...) // 追加一个切片, 切片需要解包
```




## func cap(v Type) int




## func panic(v interface{})
## func recover() interface{}

* panic和recovery是对cp
* 可以手动构造panic，需要在父函数或defer中使用recover显示处理错误
* 错误会一直往上传递，直到有recover或到达main后程序奔溃退出
* 俗称错误处理、宕机恢复
* 防止程序奔溃，不过非常严重那必须得崩溃
* 在 panic 触发的 defer 函数内，可以继续调用 panic，进一步将错误外抛，直到程序整体崩溃


recovery常用写法：

```
	defer func() {
		if err := recover(); err != nil {

			switch err.(type) {
			case runtime.Error: // 运行时错误
				fmt.Println("runtime error:", err)
			default: // 非运行时错误
				fmt.Println("error:", err)
			}

		}
	}()
```








实例：

* 构造除零异常

```
func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("出了错：", err)
			// 出了错： runtime error: integer divide by zero
		}
	}()
	myPainc()
	fmt.Printf("这里应该执行不到！")
}
func myPainc() {
	var x = 30
	var y = 0
	//panic("我就是一个大错误！")
	var c = x / y
	fmt.Println(c)
}

```

* 构造任意错误

```
func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("出了错：", err)
			//出了错： just panic right now!
		}
	}()
	myPainc()
	fmt.Printf("这里应该执行不到！")
}
func myPainc() {
	panic("just panic right now!")
}
```

* 错误传递

```
func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("出了错：", err)
			//出了错： error here
		}
	}()
	a()
	fmt.Printf("这里应该执行不到！")
}

func a() {
	b()
}
func b() {
	c()
}
func c() {
	panic("error here")
}
```


* 错误只会被一次捕获处理，不会一直传递。截胡~


```
func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("main error：", err)
			//os.Exit(1)
		}
	}()
	a()
	fmt.Printf("这里应该执行不到！")
}

func a() {
	b()
}
func b() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("catch err here")
		}
	}()
	c()
}
func c() {
	panic("error here")
}
```

输出:

```
catch err here
这里应该执行不到！
```


* 中途截胡处理异常后仍可继续抛出异常

```
func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("main error：", err)
			//os.Exit(1)
		}
	}()
	a()
	fmt.Printf("这里应该执行不到！")
}

func a() {
	b()
	panic("error in a")
}
func b() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("catch err here")
			panic("error in defer recover b")
		}
	}()
	c()
}
func c() {
	panic("error here")
}
```

输出

```
catch err here
main error： error in defer recover b
```


---
